"""Add notes to lead

Revision ID: ab19c4ae4cef
Revises: 2199e83bddb6
Create Date: 2026-07-21 01:25:32.149812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab19c4ae4cef'
down_revision: Union[str, Sequence[str], None] = '2199e83bddb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'notes')
    # ### end Alembic commands ###
